version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  text2img:
    build:
      context: ./text2img
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017/text2img
      - GCS_BUCKET=local-dev-bucket
    volumes:
      - ./data/output:/app/output
    depends_on:
      - mongodb

  img2text:
    build:
      context: ./img2text
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017/img2text
    volumes:
      - ./data/images:/app/images
    depends_on:
      - mongodb

volumes:
  mongodb_data: